Repository GDSC-SGGSCC/Hacktoberfest-22, pull requests merged in 2022-10, with the labels that each got.

#5 added C++ hello world
  C++/helloworld.cpp
Labels: hacktoberfest-accepted

#6 Added C-Sharp Project.
  C-Sharp/Alola.cs
  C-Sharp/C-Sharp.csproj
Labels: hacktoberfest-accepted

#10 Create hello-world.java
  Java/hello-world.java
Labels: hacktoberfest-accepted

#9 Create helloworld.c
  C/helloworld.c
Labels: hacktoberfest-accepted

#15 feat: add hello world in rust language
  Rust/hello-world.rs
Labels: hacktoberfest-accepted

#17 Feat: add hello world in R language
  R/helloworld.r
Labels: hacktoberfest-accepted

#18 Feat: add hello world in Swift language
  Swift/hello-world.swift
Labels: hacktoberfest-accepted

#19 Feat: add hello world in Kotlin language
  Kotlin/hello-world.kt
Labels: hacktoberfest-accepted

#21 Added ruby language
  Dart/1.dart
Labels: hacktoberfest-accepted

#23 Added HTML Hello World
  HTML/hello-world.html
Labels: hacktoberfest-accepted

#24 Create hello-world.lua
  lua/hello-world.lua
Labels: hacktoberfest-accepted

#25 Added "Hello World" program in Haskell #8
  Haskell/helloworld.hs
Labels: hacktoberfest-accepted

#27 Added hello world in Perl language
  Perl/2.pl
Labels: hacktoberfest-accepted

#28 Ruby program for Hello world
  Ruby/hello-world.rb
Labels: hacktoberfest-accepted

#26 Create Hello world.scala
  Hello world.scala
Labels: hacktoberfest-accepted

#30 Added hello world in Ada language
  Ada/hello-world.adb
Labels: hacktoberfest-accepted

#31 Added Hello World Program in Assembly and VBScript
  Assembly/Linux-x86_64.s
  VBScript/Hello_World.vbs
Labels: hacktoberfest-accepted

#32 Added hello world in Typescript
  Typescript/hello.ts
Labels: hacktoberfest-accepted

#34 Added hello world in lisp
  Lisp Language/helloworld.lsp
Labels: hacktoberfest-accepted

#37 Adding hello world program in fortran
  FORTRAN/4.exe
  FORTRAN/4.f90
Labels: hacktoberfest-accepted

#46 added hello world in erlang
  Erlang/hello-world.erl
Labels: hacktoberfest-accepted

#39 Added "hello world" in BASIC programming language
  BASIC/hello-world.bas
Labels: hacktoberfest-accepted

#22 Add Groovy Hello World
  Groovy/hello-world.groovy
  README.md
Labels: hacktoberfest-accepted

#38 Added Hello World in Brainfuck
  Brainfuck/Hello_World.bf
Labels: hacktoberfest-accepted

#44 Hello World in Solidity
  Solidity/helloworld.sol
Labels: hacktoberfest-accepted

#45 hello world in carbon
  Carbon/hello-world.carbon
Labels: hacktoberfest-accepted

#66 update auto-comment
  .github/workflows/auto-comment.yml
Labels: :mag: Ready for Review

#49 Hello World in Coffeescript
  CoffeeScript/helloworld.coffee
Labels: hacktoberfest-accepted

#51 added hello world in ocaml
  OCaml/hello-world.ml
Labels: hacktoberfest-accepted

#57 Added hello world in Objective C
  Objective C/hello-world.h
Labels: hacktoberfest-accepted

#53 Adding Hello World program in Ada
  Ada/helloworld.adb
Labels: hacktoberfest-accepted

#55 COBOL Hello World
  COBOL/helloworld.cbl
Labels: hacktoberfest-accepted

#75 Test PR
  .github/workflows/auto-comment.yml
  .github/workflows/auto-comment1.yml
Labels: :sparkles: Merged:, :mag: Ready for Review

#76 test pr
  .github/test/test.yml
Labels: :mag: Ready for Review

#82 feat: Added "Hello World" Program in Hodor Lang
  Hodor/helloworld.hd
Labels: hacktoberfest-accepted, :mag: Ready for Review

#87 Hello in Svelte
  Svelte/Hello world.svelte
Labels: hacktoberfest-accepted, :mag: Ready for Review

#89 Created Helloworld.pas
  pascal/Helloworld.pas
Labels: hacktoberfest-accepted, :mag: Ready for Review

#98 ci(Mergify): configuration update
  .mergify.yml
Labels: :mag: Ready for Review

#90 Hello world in Jython and D programming languages.
  D/helloWorld.d
  Jython/JythonHelloWorld.java
Labels: hacktoberfest-accepted, :mag: Ready for Review

#72 Added hello-world in Clojure
  Clojure/main.clj
Labels: hacktoberfest-accepted, :white_check_mark: Approved

#56 prolog hello world
  Go/hello-world.go
  Prolog/hello-world.pl
Labels: hacktoberfest-accepted, :warning: Changes requested, :white_check_mark: Approved

#83 hello in Elixir
  Elixir/hello-world.exs
Labels: hacktoberfest-accepted, :white_check_mark: Approved

#93 Added hello world in F# language
  F#/hello-world.fs
Labels: :white_check_mark: Approved

#95 Created Hello World in PL/SQL
  PL|SQL/Hello World
Labels: hacktoberfest-accepted, :white_check_mark: Approved

#109 Created Hello World in MATLAB
  MATLAB/hello_word.m
Labels: hacktoberfest-accepted, :white_check_mark: Approved

#106 Added Hello World using Power Shell
  PowerShell/helloworld.ps1
Labels: hacktoberfest-accepted, :white_check_mark: Approved

#116 add hello_world.vim in Vimscript folder
  Vimscript/hello_world.vim
Labels: hacktoberfest-accepted, :mag: Ready for Review

#113 Create BubbleSort.java
  Java/BubbleSort.java
Labels: hacktoberfest-accepted, :mag: Ready for Review

#130 Sushrut solidity branch
  Solidity/For-While-in-Solidity.sol
Labels: hacktoberfest-accepted, :mag: Ready for Review

#122 Added hello world applescript
  Applescript/hello-world.applescript
Labels: hacktoberfest-accepted, :mag: Ready for Review

#141 Created translator.py
  Python/translator.py
Labels: hacktoberfest-accepted, :mag: Ready for Review

#142 java program - Big Integer
  Java/big_Integer.java
Labels: hacktoberfest-accepted, :mag: Ready for Review

#139 added file BinarySearch.java in java
  Java/BinarySearch.java
  Java/selectionSort.java
Labels: hacktoberfest-accepted, :mag: Ready for Review

#144 Create memoryAllocTech.c
  C/memoryAllocTech.c
Labels: hacktoberfest-accepted, :mag: Ready for Review

#145 Create Menu_SelectSort_N_InsertionSort.c
  C/Menu_SelectSort_N_InsertionSort.c
Labels: hacktoberfest-accepted, :mag: Ready for Review
